import type {
  LedgerSetupMerchantAliasTemplate,
  LedgerSetupMerchantTemplate,
  LedgerSetupTemplate,
} from "internal/ledger/entity/ledgerSetupTemplate/ledgerSetupTemplate";

// 内容按 Issue #395「JPY 预设模板（定稿）」评论录入。
// 显示名使用日本正式名称（与小票一致），其他语言名称与略称放进别名。
// 同一品牌 / 服务主体只建一个商家，多场景商家通过 tagKeys 关联多个标签。

const zh = (alias: string): LedgerSetupMerchantAliasTemplate => ({
  alias,
  locale: "zh",
});
const en = (alias: string): LedgerSetupMerchantAliasTemplate => ({
  alias,
  locale: "en",
});
const ja = (alias: string): LedgerSetupMerchantAliasTemplate => ({
  alias,
  locale: "ja",
});

function merchant(
  key: string,
  name: string,
  websiteUrl: string | null,
  tagKeys: readonly string[],
  aliases: readonly LedgerSetupMerchantAliasTemplate[],
): LedgerSetupMerchantTemplate {
  return { aliases, key, name, tagKeys, websiteUrl };
}

export const jpyLedgerSetupTemplate = {
  accountCandidates: {
    bank: [
      "三菱UFJ銀行",
      "三井住友銀行",
      "みずほ銀行",
      "ゆうちょ銀行",
      "りそな銀行",
      "楽天銀行",
      "住信SBIネット銀行",
      "PayPay銀行",
      "ソニー銀行",
      "イオン銀行",
      "セブン銀行",
    ],
    credit_card: [
      "楽天カード",
      "三井住友カード",
      "JCBカード",
      "イオンカード",
      "dカード",
      "au PAYカード",
      "PayPayカード",
      "エポスカード",
      "セゾンカード",
      "アメリカン・エキスプレス",
    ],
    e_money: [
      "PayPay",
      "楽天ペイ",
      "d払い",
      "au PAY",
      "メルペイ",
      "Suica",
      "PASMO",
      "ICOCA",
      "nanaco",
      "WAON",
      "楽天Edy",
    ],
  },
  currency: "JPY",
  merchantTags: [
    {
      defaultSelected: true,
      icon: "🛒",
      key: "supermarket",
      name: "超市",
      sortOrder: 0,
    },
    {
      defaultSelected: true,
      icon: "🏪",
      key: "convenience_store",
      name: "便利店",
      sortOrder: 1,
    },
    {
      defaultSelected: true,
      icon: "🍽️",
      key: "restaurant",
      name: "餐饮",
      sortOrder: 2,
    },
    {
      defaultSelected: true,
      icon: "☕",
      key: "cafe",
      name: "咖啡甜品",
      sortOrder: 3,
    },
    {
      defaultSelected: true,
      icon: "💊",
      key: "drugstore",
      name: "药妆店",
      sortOrder: 4,
    },
    {
      defaultSelected: true,
      icon: "🏠",
      key: "household",
      name: "生活杂货",
      sortOrder: 5,
    },
    {
      defaultSelected: false,
      icon: "👕",
      key: "apparel",
      name: "服饰",
      sortOrder: 6,
    },
    {
      defaultSelected: false,
      icon: "🔌",
      key: "electronics",
      name: "家电数码",
      sortOrder: 7,
    },
    {
      defaultSelected: true,
      icon: "📦",
      key: "ecommerce",
      name: "电商",
      sortOrder: 8,
    },
    {
      defaultSelected: false,
      icon: "🚃",
      key: "transport",
      name: "交通",
      sortOrder: 9,
    },
    {
      defaultSelected: false,
      icon: "📶",
      key: "telecom",
      name: "通讯",
      sortOrder: 10,
    },
    {
      defaultSelected: false,
      icon: "🎬",
      key: "subscription",
      name: "订阅服务",
      sortOrder: 11,
    },
    {
      defaultSelected: false,
      icon: "⚡",
      key: "utilities",
      name: "水电燃气",
      sortOrder: 12,
    },
    {
      defaultSelected: false,
      icon: "🏛️",
      key: "public_service",
      name: "政府·公共服务",
      sortOrder: 13,
    },
  ],
  merchants: [
    // 超市
    merchant(
      "aeon",
      "イオン",
      "https://www.aeon.com/",
      ["supermarket"],
      [zh("永旺"), en("AEON"), ja("イオンスタイル")],
    ),
    merchant(
      "ito_yokado",
      "イトーヨーカドー",
      "https://www.itoyokado.co.jp/",
      ["supermarket"],
      [zh("伊藤洋华堂"), en("Ito-Yokado"), ja("ヨーカドー")],
    ),
    merchant(
      "seiyu",
      "西友",
      "https://www.seiyu.co.jp/",
      ["supermarket"],
      [en("SEIYU"), ja("せいゆう")],
    ),
    merchant(
      "life",
      "ライフ",
      "https://www.lifecorp.jp/",
      ["supermarket"],
      [en("LIFE")],
    ),
    merchant(
      "gyomu_super",
      "業務スーパー",
      "https://www.gyomusuper.jp/",
      ["supermarket"],
      [zh("业务超市"), ja("業スー")],
    ),
    merchant(
      "costco",
      "コストコ",
      "https://www.costco.co.jp/",
      ["supermarket"],
      [zh("好市多"), en("Costco")],
    ),
    // 运营主体按地区分为多家公司，没有统一的官网首页，URL 置空。
    merchant(
      "maxvalu",
      "マックスバリュ",
      null,
      ["supermarket"],
      [en("MaxValu")],
    ),
    // 便利店
    merchant(
      "seven_eleven",
      "セブン-イレブン",
      "https://www.sej.co.jp/",
      ["convenience_store"],
      [zh("711"), en("7-Eleven"), ja("セブン"), ja("セブンイレブン")],
    ),
    merchant(
      "familymart",
      "ファミリーマート",
      "https://www.family.co.jp/",
      ["convenience_store"],
      [zh("全家"), en("FamilyMart"), ja("ファミマ")],
    ),
    merchant(
      "lawson",
      "ローソン",
      "https://www.lawson.co.jp/",
      ["convenience_store"],
      [zh("罗森"), en("LAWSON")],
    ),
    merchant(
      "ministop",
      "ミニストップ",
      "https://www.ministop.co.jp/",
      ["convenience_store"],
      [en("MINISTOP")],
    ),
    merchant(
      "daily_yamazaki",
      "デイリーヤマザキ",
      "https://www.daily-yamazaki.jp/",
      ["convenience_store"],
      [en("Daily Yamazaki"), ja("デイリー")],
    ),
    // 餐饮
    merchant(
      "mcdonalds",
      "マクドナルド",
      "https://www.mcdonalds.co.jp/",
      ["restaurant"],
      [zh("麦当劳"), en("McDonald's"), ja("マック"), ja("マクド")],
    ),
    merchant(
      "yoshinoya",
      "吉野家",
      "https://www.yoshinoya.com/",
      ["restaurant"],
      [en("Yoshinoya")],
    ),
    merchant(
      "sukiya",
      "すき家",
      "https://www.sukiya.jp/",
      ["restaurant"],
      [en("Sukiya")],
    ),
    merchant(
      "matsuya",
      "松屋",
      "https://www.matsuyafoods.co.jp/",
      ["restaurant"],
      [en("Matsuya")],
    ),
    merchant(
      "saizeriya",
      "サイゼリヤ",
      "https://www.saizeriya.co.jp/",
      ["restaurant"],
      [zh("萨莉亚"), en("Saizeriya")],
    ),
    merchant(
      "gusto",
      "ガスト",
      "https://www.skylark.co.jp/gusto/",
      ["restaurant"],
      [en("Gusto")],
    ),
    merchant(
      "sushiro",
      "スシロー",
      "https://www.akindo-sushiro.co.jp/",
      ["restaurant"],
      [zh("寿司郎"), en("Sushiro")],
    ),
    merchant(
      "kura_sushi",
      "くら寿司",
      "https://www.kurasushi.co.jp/",
      ["restaurant"],
      [zh("藏寿司"), en("Kura Sushi")],
    ),
    merchant(
      "hama_sushi",
      "はま寿司",
      "https://www.hama-sushi.co.jp/",
      ["restaurant"],
      [zh("滨寿司"), en("Hama Sushi")],
    ),
    merchant(
      "marugame",
      "丸亀製麺",
      "https://www.marugame.com/",
      ["restaurant"],
      [zh("丸龟制面"), en("Marugame")],
    ),
    merchant(
      "coco_ichibanya",
      "CoCo壱番屋",
      "https://www.ichibanya.co.jp/",
      ["restaurant"],
      [zh("CoCo壹番屋"), ja("ココイチ")],
    ),
    merchant(
      "kfc",
      "ケンタッキーフライドチキン",
      "https://www.kfc.co.jp/",
      ["restaurant"],
      [zh("肯德基"), en("KFC"), ja("ケンタッキー")],
    ),
    merchant(
      "mos_burger",
      "モスバーガー",
      "https://www.mos.jp/",
      ["restaurant"],
      [zh("摩斯汉堡"), en("MOS BURGER"), ja("モス")],
    ),
    // 咖啡甜品
    merchant(
      "starbucks",
      "スターバックス",
      "https://www.starbucks.co.jp/",
      ["cafe"],
      [zh("星巴克"), en("Starbucks"), ja("スタバ")],
    ),
    merchant(
      "doutor",
      "ドトールコーヒー",
      "https://www.doutor.co.jp/",
      ["cafe"],
      [zh("罗多伦"), en("DOUTOR"), ja("ドトール")],
    ),
    merchant(
      "komeda",
      "コメダ珈琲店",
      "https://www.komeda.co.jp/",
      ["cafe"],
      [zh("客美多"), en("Komeda"), ja("コメダ")],
    ),
    merchant(
      "tullys",
      "タリーズコーヒー",
      "https://www.tullys.co.jp/",
      ["cafe"],
      [en("Tully's"), ja("タリーズ")],
    ),
    merchant(
      "mister_donut",
      "ミスタードーナツ",
      "https://www.misterdonut.jp/",
      ["cafe"],
      [zh("美仕唐纳滋"), en("Mister Donut"), ja("ミスド")],
    ),
    // 药妆店
    merchant(
      "matsumoto_kiyoshi",
      "マツモトキヨシ",
      "https://www.matsukiyo.co.jp/",
      ["drugstore"],
      [zh("松本清"), ja("マツキヨ")],
    ),
    // 定稿中的域名已无法解析，且无法确认替代官网，URL 置空。
    merchant(
      "cocokara_fine",
      "ココカラファイン",
      null,
      ["drugstore"],
      [ja("ココカラ")],
    ),
    merchant(
      "welcia",
      "ウエルシア",
      "https://www.welcia.co.jp/",
      ["drugstore"],
      [zh("威尔洗"), en("Welcia")],
    ),
    merchant(
      "tsuruha",
      "ツルハドラッグ",
      "https://www.tsuruha.co.jp/",
      ["drugstore"],
      [zh("鹤羽药妆"), ja("ツルハ")],
    ),
    merchant(
      "sugi",
      "スギ薬局",
      "https://www.sugi-net.jp/",
      ["drugstore"],
      [zh("杉药局"), ja("スギ")],
    ),
    merchant(
      "sundrug",
      "サンドラッグ",
      "https://www.sundrug.co.jp/",
      ["drugstore"],
      [en("SUNDRUG")],
    ),
    merchant(
      "cosmos",
      "ドラッグストアコスモス",
      "https://www.cosmospc.co.jp/",
      ["drugstore"],
      [ja("コスモス")],
    ),
    // 生活杂货
    merchant(
      "daiso",
      "ダイソー",
      "https://www.daiso-sangyo.co.jp/",
      ["household"],
      [zh("大创"), en("DAISO")],
    ),
    merchant(
      "seria",
      "セリア",
      "https://www.seria-group.com/",
      ["household"],
      [en("Seria")],
    ),
    merchant(
      "cando",
      "キャンドゥ",
      "https://www.cando-web.co.jp/",
      ["household"],
      [en("Can★Do"), en("Can Do")],
    ),
    merchant(
      "nitori",
      "ニトリ",
      "https://www.nitori.co.jp/",
      ["household"],
      [zh("宜得利"), en("NITORI")],
    ),
    merchant(
      "muji",
      "無印良品",
      "https://www.muji.com/jp/",
      ["household"],
      [zh("无印良品"), en("MUJI")],
    ),
    merchant(
      "don_quijote",
      "ドン・キホーテ",
      "https://www.donki.com/",
      ["household"],
      [zh("堂吉诃德"), ja("ドンキ"), en("Don Quijote")],
    ),
    merchant(
      "loft",
      "ロフト",
      "https://www.loft.co.jp/",
      ["household"],
      [en("LoFt")],
    ),
    merchant(
      "hands",
      "ハンズ",
      "https://www.hands.net/",
      ["household"],
      [zh("东急手创"), ja("東急ハンズ"), en("HANDS")],
    ),
    // 服饰
    merchant(
      "uniqlo",
      "ユニクロ",
      "https://www.uniqlo.com/jp/",
      ["apparel"],
      [zh("优衣库"), en("UNIQLO")],
    ),
    merchant(
      "gu",
      "GU",
      "https://www.gu-global.com/jp/",
      ["apparel"],
      [ja("ジーユー")],
    ),
    merchant(
      "shimamura",
      "しまむら",
      "https://www.shimamura.gr.jp/",
      ["apparel"],
      [zh("岛村"), en("Shimamura")],
    ),
    merchant(
      "workman",
      "ワークマン",
      "https://www.workman.co.jp/",
      ["apparel"],
      [en("WORKMAN")],
    ),
    merchant(
      "zara",
      "ZARA",
      "https://www.zara.com/jp/",
      ["apparel"],
      [ja("ザラ")],
    ),
    merchant(
      "nishimatsuya",
      "西松屋",
      "https://www.24028.jp/",
      ["apparel"],
      [en("Nishimatsuya")],
    ),
    // 家电数码
    merchant(
      "yodobashi",
      "ヨドバシカメラ",
      "https://www.yodobashi.com/",
      ["electronics"],
      [zh("友都八喜"), ja("ヨドバシ")],
    ),
    merchant(
      "bic_camera",
      "ビックカメラ",
      "https://www.biccamera.com/",
      ["electronics"],
      [zh("必酷"), ja("ビック"), en("BicCamera")],
    ),
    merchant(
      "yamada_denki",
      "ヤマダデンキ",
      "https://www.yamada-denki.jp/",
      ["electronics"],
      [zh("山田电机"), ja("ヤマダ")],
    ),
    merchant(
      "edion",
      "エディオン",
      "https://www.edion.com/",
      ["electronics"],
      [zh("爱电王"), en("EDION")],
    ),
    merchant(
      "ks_denki",
      "ケーズデンキ",
      "https://www.ksdenki.com/",
      ["electronics"],
      [en("K's")],
    ),
    merchant(
      "apple",
      "Apple",
      "https://www.apple.com/jp/",
      ["electronics", "subscription"],
      [
        zh("苹果"),
        ja("アップル"),
        en("App Store"),
        en("iCloud"),
        en("Apple Music"),
      ],
    ),
    // 电商
    merchant(
      "amazon",
      "Amazon",
      "https://www.amazon.co.jp/",
      ["ecommerce", "subscription"],
      [
        zh("亚马逊"),
        ja("アマゾン"),
        ja("Amazonプライム"),
        en("Prime Video"),
        zh("亚马逊Prime"),
      ],
    ),
    merchant(
      "rakuten",
      "楽天",
      "https://www.rakuten.co.jp/",
      ["ecommerce", "telecom"],
      [
        zh("乐天"),
        en("Rakuten"),
        ja("楽天市場"),
        ja("楽天モバイル"),
        ja("楽天トラベル"),
      ],
    ),
    merchant(
      "yahoo_shopping",
      "Yahoo!ショッピング",
      "https://shopping.yahoo.co.jp/",
      ["ecommerce"],
      [zh("雅虎购物"), ja("ヤフショ")],
    ),
    merchant(
      "mercari",
      "メルカリ",
      "https://jp.mercari.com/",
      ["ecommerce"],
      [zh("煤炉"), en("Mercari")],
    ),
    merchant(
      "zozotown",
      "ZOZOTOWN",
      "https://zozo.jp/",
      ["ecommerce"],
      [ja("ゾゾタウン"), en("ZOZO")],
    ),
    // 交通
    merchant(
      "jr_east",
      "JR東日本",
      "https://www.jreast.co.jp/",
      ["transport"],
      [zh("JR东日本"), en("JR East")],
    ),
    merchant(
      "jr_central",
      "JR東海",
      "https://jr-central.co.jp/",
      ["transport"],
      [zh("JR东海"), en("JR Central")],
    ),
    merchant(
      "jr_west",
      "JR西日本",
      "https://www.westjr.co.jp/",
      ["transport"],
      [en("JR West")],
    ),
    merchant(
      "go_taxi",
      "GO",
      "https://go.goinc.jp/",
      ["transport"],
      [ja("GOタクシー"), zh("打车")],
    ),
    merchant(
      "eneos",
      "ENEOS",
      "https://www.eneos.co.jp/",
      ["transport"],
      [ja("エネオス"), zh("加油站")],
    ),
    merchant(
      "idemitsu",
      "出光",
      "https://www.idemitsu.com/jp/",
      ["transport"],
      [ja("出光興産"), en("apollostation")],
    ),
    // 通讯（楽天与电商共用同一商家）
    merchant(
      "docomo",
      "docomo",
      "https://www.docomo.ne.jp/",
      ["telecom"],
      [ja("ドコモ"), ja("NTTドコモ"), en("ahamo"), ja("アハモ")],
    ),
    merchant(
      "au",
      "au",
      "https://www.au.com/",
      ["telecom"],
      [
        ja("エーユー"),
        en("KDDI"),
        en("UQ mobile"),
        ja("UQモバイル"),
        en("povo"),
      ],
    ),
    merchant(
      "softbank",
      "SoftBank",
      "https://www.softbank.jp/",
      ["telecom"],
      [
        zh("软银"),
        ja("ソフトバンク"),
        en("Y!mobile"),
        ja("ワイモバイル"),
        en("LINEMO"),
      ],
    ),
    // 订阅服务（Amazon、Apple 与其他标签共用同一商家）
    merchant(
      "netflix",
      "Netflix",
      "https://www.netflix.com/jp/",
      ["subscription"],
      [zh("网飞"), ja("ネットフリックス")],
    ),
    merchant(
      "spotify",
      "Spotify",
      "https://www.spotify.com/jp/",
      ["subscription"],
      [ja("スポティファイ")],
    ),
    merchant(
      "google",
      "Google",
      "https://www.google.com/",
      ["subscription"],
      [
        zh("谷歌"),
        en("YouTube Premium"),
        en("YouTube"),
        en("Google Play"),
        en("Google One"),
        zh("油管会员"),
      ],
    ),
    merchant(
      "disney_plus",
      "Disney+",
      "https://www.disneyplus.com/ja-jp",
      ["subscription"],
      [ja("ディズニープラス")],
    ),
    merchant(
      "u_next",
      "U-NEXT",
      "https://video.unext.jp/",
      ["subscription"],
      [ja("ユーネクスト")],
    ),
    // 水电燃气
    merchant(
      "tepco",
      "東京電力",
      "https://www.tepco.co.jp/",
      ["utilities"],
      [
        zh("东京电力"),
        en("TEPCO"),
        ja("東京電力エナジーパートナー"),
        ja("電気代"),
      ],
    ),
    merchant(
      "kepco",
      "関西電力",
      "https://www.kepco.co.jp/",
      ["utilities"],
      [zh("关西电力"), en("KEPCO"), ja("関電")],
    ),
    merchant(
      "chuden",
      "中部電力",
      "https://www.chuden.co.jp/",
      ["utilities"],
      [zh("中部电力"), ja("中部電力ミライズ"), ja("中電")],
    ),
    merchant(
      "kyuden",
      "九州電力",
      "https://www.kyuden.co.jp/",
      ["utilities"],
      [zh("九州电力"), ja("九電")],
    ),
    merchant(
      "tohoku_epco",
      "東北電力",
      "https://www.tohoku-epco.co.jp/",
      ["utilities"],
      [zh("东北电力")],
    ),
    merchant(
      "tokyo_gas",
      "東京ガス",
      "https://www.tokyo-gas.co.jp/",
      ["utilities"],
      [zh("东京燃气"), en("Tokyo Gas"), ja("ガス代")],
    ),
    merchant(
      "osaka_gas",
      "大阪ガス",
      "https://www.osakagas.co.jp/",
      ["utilities"],
      [zh("大阪燃气"), en("Osaka Gas"), ja("大ガス")],
    ),
    merchant(
      "toho_gas",
      "東邦ガス",
      "https://www.tohogas.co.jp/",
      ["utilities"],
      [zh("东邦燃气")],
    ),
    // 通用商家，用户创建后可改名为所在城市的水道局。
    merchant(
      "water_bureau",
      "水道局",
      null,
      ["utilities"],
      [zh("自来水"), ja("水道代"), ja("上下水道")],
    ),
    // 政府·公共服务
    merchant(
      "city_office",
      "市区町村役所",
      null,
      ["public_service"],
      [
        ja("市役所"),
        ja("区役所"),
        ja("町役場"),
        ja("住民税"),
        ja("国民健康保険"),
        zh("市政府"),
      ],
    ),
    merchant(
      "prefectural_tax_office",
      "都道府県税事務所",
      null,
      ["public_service"],
      [
        ja("県税事務所"),
        ja("都税事務所"),
        ja("自動車税"),
        zh("府政府"),
        zh("县政府"),
      ],
    ),
    merchant(
      "tax_office",
      "税務署",
      "https://www.nta.go.jp/",
      ["public_service"],
      [ja("国税庁"), ja("所得税"), zh("确定申报"), ja("確定申告")],
    ),
    merchant(
      "japan_pension_service",
      "日本年金機構",
      "https://www.nenkin.go.jp/",
      ["public_service"],
      [ja("年金"), ja("国民年金"), ja("厚生年金"), zh("养老金")],
    ),
    merchant(
      "immigration_services_agency",
      "出入国在留管理庁",
      "https://www.moj.go.jp/isa/",
      ["public_service"],
      [ja("入管"), ja("入国管理局"), zh("出入国管理局"), zh("签证")],
    ),
    merchant(
      "post_office",
      "郵便局",
      "https://www.post.japanpost.jp/",
      ["public_service"],
      [zh("邮局"), ja("日本郵便"), en("Japan Post"), ja("ゆうパック")],
    ),
    merchant(
      "nhk",
      "NHK",
      "https://www.nhk.or.jp/",
      ["public_service"],
      [ja("受信料"), zh("日本放送协会")],
    ),
    merchant(
      "hospital",
      "病院",
      null,
      ["public_service"],
      [zh("医院"), ja("クリニック"), ja("診療所")],
    ),
    merchant(
      "pharmacy",
      "薬局",
      null,
      ["public_service"],
      [zh("药局"), ja("調剤薬局")],
    ),
  ],
  version: 1,
} as const satisfies LedgerSetupTemplate;
