export const merchantText = {
  addAlias: "添加别名",
  aliasHelper: "别名既可作为展示名候选，也会用于搜索匹配。",
  aliasLabel: "别名",
  archive: "归档商家",
  archiveConfirmTitle: "归档商家？",
  archiveAliasErrorTitle: "商家别名移除失败",
  archiveDescription: "归档后不会出现在新的记账选项中，既有记录仍会保留。",
  archiveErrorTitle: "商家归档失败",
  create: "新增商家",
  createAliasErrorTitle: "商家别名新增失败",
  createErrorTitle: "商家新增失败",
  currentDisplayName: "当前展示名",
  edit: "编辑商家",
  editErrorTitle: "商家更新失败",
  formalName: "正式名",
  iconError: "未能获取网站图标，已使用默认商家头像",
  iconIdle: "填写商家网址后会自动获取头像",
  iconLoading: "正在获取网站图标",
  iconRefresh: "重新获取商家头像",
  iconSuccess: "已通过网站图标自动获取头像",
  nameLabel: "商家名称",
  namePlaceholder: "例如：Amazon",
  manageTags: "管理标签",
  tagsLabel: "商家标签",
  tagsHelper: "可选择多个标签，便于在商家列表中筛选。",
  noteLabel: "备注（可选）",
  notePlaceholder: "例如：日常购物与杂货采购",
  preferredHelper: "选择记账和列表中优先显示的名称。未选择别名时使用正式名。",
  preferredErrorTitle: "展示名更新失败",
  preferredTitle: "显示名",
  save: "保存修改",
  websiteHelper: "保存后会通过安全的 favicon 服务自动获取头像。",
  websiteLabel: "商家网址",
  websitePlaceholder: "例如：https://www.example.com",
} as const;
