export const merchantText = {
  addAlias: "添加别名",
  aliasHelper: "别名既可作为展示名候选，也会用于搜索匹配。",
  aliasLabel: "别名",
  archive: "归档商家",
  archiveAliasErrorTitle: "商家别名移除失败",
  archiveDescription: "归档后不会出现在新的记账选项中，既有记录仍会保留。",
  archiveErrorTitle: "商家归档失败",
  create: "新增商家",
  createAliasErrorTitle: "商家别名新增失败",
  createErrorTitle: "商家新增失败",
  edit: "编辑商家",
  editErrorTitle: "商家更新失败",
  formalName: "正式名",
  nameLabel: "商家名称",
  noteLabel: "备注（可选）",
  preferredHelper: "选择记账和列表中优先显示的名称。未选择别名时使用正式名。",
  preferredErrorTitle: "展示名更新失败",
  preferredTitle: "显示名",
  save: "保存修改",
  websiteHelper: "保存后会通过安全的 favicon 服务自动获取头像。",
  websiteLabel: "商家网址",
} as const;
